const { ethers } = require("hardhat");
const fs = require("fs");
const snarkjs = require("snarkjs");

// Note we should execute at the dir hardhat/
describe("Verifier Contract Gas Test", function () {
  let verifier;
  let Verifier;
  let verifier_addr;

  before(async function () {
    // the verifier.sol in the dir contracts is generated by the sh script in groth16
    Verifier = await ethers.getContractFactory(
      "contracts/verifier.sol:Groth16Verifier"
    );
    verifier = await Verifier.deploy();
    const deployed_verifier = await verifier.waitForDeployment();
    const verifier_addr = await deployed_verifier.getAddress();
    console.log("verifier.sol is deployed to:", verifier_addr);
  });

  it("should test gas consumption", async function () {
    // convert groth16 proof (generated by the sh script in groth16) to calldata onchain
    const proof = JSON.parse(
      fs.readFileSync("../groth16/build/proof.json", "utf8")
    );
    const publicSignals = JSON.parse(
      fs.readFileSync("../groth16/build/public.json", "utf8")
    );

    // first, verify the proof using node
    const vKey = JSON.parse(
      fs.readFileSync("../groth16/build/verification_key.json")
    );

    const res = await snarkjs.groth16.verify(vKey, publicSignals, proof);

    if (res === true) {
      console.log("Pre-Verification OK");
    } else {
      console.log("Invalid proof");
    }

    const calldata = await snarkjs.groth16.exportSolidityCallData(
      proof,
      publicSignals
    );
    let jsonCalldata = JSON.parse("[" + calldata + "]");
    console.log("publicSignals: ");
    console.log(publicSignals);

    // finally, we estimate the gas consumption using the generated proof and the generated verifier.sol
    async function try_estimateGas() {
      try {
        const gas_consumption = await verifier.verifyProof.estimateGas(
          jsonCalldata[0],
          jsonCalldata[1],
          jsonCalldata[2],
          jsonCalldata[3]
        );
        console.log(`Estimated Gas: ${gas_consumption.toString()}`);
      } catch (error) {
        console.error(`Error estimating gas: ${error}`);
      }
    }

    await try_estimateGas();
  });
});
